---
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  - name: ubuntu
    image: pycontribs/ubuntu:latest
    pre_build_image: true
  - name: centos
    image: pycontribs/centos:7
    pre_build_image: true
